#!/usr/bin/env ruby
# frozen_string_literal: true

# Prevent failures from being reported twice.
Thread.report_on_exception = false

require_relative "../lib/kraaken"

begin
  Kraaken::Cli::Main.start(ARGV)
rescue => e
  puts "  \e[31mERROR (#{e.class}): #{e.message}\e[0m"
  puts e.backtrace
  exit 1
rescue Interrupt
  exit 0
end
